from datetime import datetime
from .. import db

class Activity(db.Model):
    __tablename__ = 'activities'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    track_id = db.Column(db.Integer, db.ForeignKey('tracks.id'), nullable=False)
    name = db.Column(db.String(200), unique=True, nullable=True)
    description = db.Column(db.String(2000), nullable=True)
    start_time_local = db.Column(db.DateTime(), nullable=True)
    start_time_utc = db.Column(db.DateTime(), nullable=True)
    distance = db.Column(db.Float, nullable=False)
    duration = db.Column(db.Float, nullable=False)
    gps_screen_path = db.Column(db.String(200), unique=True, nullable=True)
    start_latitude = db.Column(db.Float, nullable=True)
    start_longitude = db.Column(db.Float, nullable=True)
    end_latitude = db.Column(db.Float, nullable=True)
    end_longitude = db.Column(db.Float, nullable=True)
    moving_duration = db.Column(db.Float, nullable=True)
    elapsed_duration = db.Column(db.Float, nullable=True)
    elevation_gain = db.Column(db.Float, nullable=True)
    elevation_loss = db.Column(db.Float, nullable=True)
    max_elevation = db.Column(db.Float, nullable=True)
    min_elevation = db.Column(db.Float, nullable=True)
    average_speed = db.Column(db.Float, nullable=True)
    average_moving_Speed = db.Column(db.Float, nullable=True)
    max_speed = db.Column(db.Float, nullable=True)
    calories = db.Column(db.Integer, nullable=True)
    average_hr = db.Column(db.Integer, nullable=True)
    max_hraverage_hr = db.Column(db.Integer, nullable=True)
    average_run_cadence = db.Column(db.Float, nullable=True)
    max_run_cadence = db.Column(db.Integer, nullable=True)
    ground_contact_time = db.Column(db.Float, nullable=True)
    stride_length = db.Column(db.Float, nullable=True)
    vertical_oscillation = db.Column(db.Float, nullable=True)
    training_effect = db.Column(db.Float, nullable=True)
    max_vertical_speed = db.Column(db.Float, nullable=True)
    min_activity_lap_duration = db.Column(db.Float, nullable=True)
    created = db.Column(db.DateTime(), nullable=False, default=datetime.utcnow)
    
